name: Dots.eco Unity SDK Build Action

on: [pull_request]

jobs:
  testAllModes:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./
          githubToken: ${{ secrets.DOTS_UNITY_GITHUB_TOKEN }}
          testMode: EditMode
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts
